name: Docker Image CI
on:
  push:
    branches: [ "production" ]
jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}"
          push: true
          tags: licon4812/awc_text_game:latest
          
  Deploy:
      runs-on: ubuntu-latest
      needs: docker
      defaults:
        run:
          working-directory: ./
      steps:
       -
        name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            docker ps -aq | xargs docker stop | xargs docker rm
            docker pull licon4812/awc_text_game:latest
            docker run -d -p57575:57575 licon4812/awc_text_game:latest
