name: Docker Image CI
on:
  push:
    branches: [ "production" ]
jobs:
  docker:
    runs-on: windows-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: List directory
        run: ls
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build
        run: |
                  docker build -t licon4812/awc_text_game .
      - name: Docker Push
        run: |
                docker push licon4812/awc_text_game 
          
  Deploy:
      runs-on: ubuntu-latest
      needs: docker
      steps:
       -
        name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            docker ps -aq | xargs docker stop | xargs docker rm
            docker pull licon4812/awc_text_game:latest
            docker run -d -p57575:57575 licon4812/awc_text_game:latest
